name: subspace_relay_mobile
description: "Subspace Relay"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  async: ^2.13.0
  plugin_platform_interface: ^2.1.8
  hooks_riverpod: ^3.3.2
  flutter_hooks: ^0.21.3
  riverpod_annotation: ^4.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  package_info_plus: ^10.1.0
  app_links: ^7.1.2

  subspace_relay_pb: ^1.0.11
  protobuf: ^6.0.0
  mqtt5_client: ^4.14.0
  uuid: ^4.5.1
  cryptography_plus: ^3.0.0
  cryptography_flutter_plus: ^3.0.0
  nfc_manager: ^4.2.1

  convert: ^3.1.2
  typed_data: ^1.4.0
  collection: ^1.19.1
  vibration: ^3.1.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.4
  build_runner: ^2.5.4
  riverpod_lint: ^3.1.4
  freezed: ^3.1.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
