name: subspace_relay_mobile
description: "Subspace Relay"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  plugin_platform_interface: ^2.1.8
  hooks_riverpod: ^3.0.0
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  cryptography_plus: ^2.7.1
  cryptography_flutter_plus: ^2.3.4
  freezed_annotation: ^3.1.0

  protobuf: ^4.1.0
  mqtt5_client: ^4.14.0
  uuid: ^4.5.1

  subspacerelay:
    git:
      url: https://github.com/nvx/subspace-relay.git
      ref: v0.0.4
      path: dart
  convert: ^3.1.2
  typed_data: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
  freezed: ^3.1.0

flutter:
  uses-material-design: true
